# Generated by Django 5.0.6 on 2024-07-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('telegram', models.CharField(max_length=100)),
                ('graduation_year', models.IntegerField()),
            ],
        ),
    ]
