# Generated by Django 5.0.6 on 2024-06-22 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_customuser_groups_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
