# Generated by Django 5.0.7 on 2024-07-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_customuser_activities_customuser_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_photo',
            field=models.ImageField(blank=True, upload_to='profile_pics/'),
        ),
    ]
