# Generated by Django 5.0.6 on 2024-06-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0002_profile_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='graduation_year',
            field=models.IntegerField(default=2015),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(default='-', max_length=255),
        ),
    ]
