# Generated by Django 5.0.6 on 2024-06-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0003_profile_user_photo_alter_profile_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_photo',
            field=models.ImageField(blank=True, default='alumni/static/alumni/pictures/user_photo.png', null=True, upload_to='profile_pics'),
        ),
    ]
