# Generated by Django 5.0.6 on 2024-06-30 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0004_alter_profile_user_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
