# Generated by Django 5.0.6 on 2024-07-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=200)),
                ('author_email', models.EmailField(max_length=254)),
                ('author_name', models.CharField(max_length=100)),
                ('author_surname', models.CharField(max_length=100)),
                ('author_alias', models.CharField(max_length=100)),
                ('picture', models.ImageField(default='event_pics/default_event_img.svg', upload_to='event_pics/')),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('description', models.TextField()),
                ('link', models.URLField(blank=True)),
                ('tags', models.JSONField()),
            ],
        ),
    ]
