name: Pipeline

on:
  push:
    branches:
      - CI/CD-pipeline

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
      EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
      EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.13

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up database
        run: |
          cd alumni
          python manage.py makemigrations --noinput
          python manage.py migrate --noinput

      - name: Collect static files
        run: |
          cd alumni
          python manage.py collectstatic --noinput

      - name: Run tests
        run: |
            python manage.py test