name: Pipeline

on:
  push:
    branches:
      - CI/CD-pipeline

jobs:
  build:
    runs-on: self-hosted

    env:
      EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
      EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
      EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.3

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up database
        run: |
          cd alumni
          python manage.py makemigrations --noinput
          python manage.py migrate --noinput

      - name: Collect static files
        run: |
          cd alumni
          python manage.py collectstatic --noinput

      - name: Clean up Docker
        if: always()
        run: docker system prune -af

  test:
    runs-on: self-hosted

    needs: build

    env:
      EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
      EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
      EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.3

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up database
        run: |
          cd alumni
          python manage.py makemigrations --noinput
          python manage.py migrate --noinput

      - name: Collect static files
        run: |
          cd alumni
          python manage.py collectstatic --noinput

      - name: Run tests
        run: |
          cd alumni
          python manage.py test

      - name: Clean up Docker
        if: always()
        run: sudo docker system prune -af

  deploy:
    runs-on: self-hosted

    needs: test

    env:
      EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
      EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
      EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.3

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up database
        run: |
          cd alumni
          python manage.py makemigrations --noinput
          python manage.py migrate --noinput

      - name: Collect static files
        run: |
          cd alumni
          python manage.py collectstatic --noinput

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-django-app:latest

      - name: Connect to VM via SSH and Deploy Docker Container
        uses: appleboy/ssh-action@master
        with:
          host: 130.193.43.164
          username: angelika
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          port: 22
          script: |
            sudo docker rm -f alumni
            sudo echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            sudo docker pull "${{ secrets.DOCKER_USERNAME }}"/my-django-app:latest
            sudo docker run -d --name alumni -p 80:8000 "${{ secrets.DOCKER_USERNAME }}"/my-django-app:latest

      - name: Clean up Docker
        if: always()
        run: docker system prune -af